# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0  # Pin to ensure that we don't run into any breaking changes on commit
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.4.4
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        # Always run ovr the whole os3_rll module
        pass_filenames: false
        args: [vnet_manager]
