# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0  # Pin to ensure that we don't run into any breaking changes on commit
    hooks:
      - id: black
        language_version: python3.6
