language: python
virtualenv:
    system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-apt
python:
    - "3.6"
    - "3.8"
install: pip install tox-travis
script: tox
