language: python
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-apt intltool libapt-pkg-dev
  - pip install -U pip setuptools
  - pip install -U wheel
  # Install some reqs first, needed for the compile
  - pip install "Sphinx==3.1.2"
  - pip install git+https://salsa.debian.org/python-team/modules/python-distutils-extra.git@c8cf85a9c86f7f62c47b38b1141e2269b96829a6
python:
    - "3.6"
    - "3.8"
install: pip install -r requirements/test.txt
before_script: "black --check --diff --line-length 140 --target-version py36 vnet_manager"
script: "pytest && pylint vnet_manager"
