language: python
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-apt intltool libapt-pkg-dev
python:
    - "3.6"
    - "3.8"
install: pip install -r requirements/test.txt
before_script: "black --check --diff --line-length 140 --target-version py36 vnet_manager"
script: "pytest; pylint vnet_manager"
