---
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: "Default LXD bridge"
  managed: false
  name: lxdbr0
  type: ""
storage_pools:
- config:
    size: 30GB
  description: "Default LXD storage pool"
  name: default
  driver: btrfs
profiles:
- config: {}
  description: "Default LXD profile"
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
