providers:
  lxc:
    supported_operating_systems:
      - "bionic"
      - "focal"
    dns-nameserver: 8.8.8.8
    required_host_packages:
      - lxd
      - lxc
      - screen
      - tmux
      - bridge-utils
      - tcpdump
      - net-tools
      - curl
      - btrfs-tools
    guest_packages:
      - man
      - net-tools
      - traceroute
      - nano
      - vim
      - bridge-utils
      - radvd
      - frr
      - frr-pythontools
    base_image:
      os: "18.04"
      server: "https://cloud-images.ubuntu.com/daily"
      protocol: simplestreams
