---

#   host10 ---- vnet-br0 ---- host20

switches: 1

machines:
  host10:
    type: host
    interfaces:
      eth1:
        ipv4: 10.0.101.1/24
        mac: 00:00:00:00:11:11
        bridge: 0
    vlans:
      vlan.10:
        id: 10
        link: eth1
        addresses:
          - 10.0.10.1/24
      vlan.20:
        id: 20
        link: eth1
        addresses:
          - 10.0.20.1/24
      vlan.30:
        id: 30
        link: eth1
        addresses:
          - 10.0.30.1/24
  host20:
    type: host
    interfaces:
      eth2:
        ipv4: 10.0.202.2/24
        mac: 00:00:00:00:22:22
        bridge: 0
    vlans:
      vlan.10:
        id: 10
        link: eth2
        addresses:
          - 10.0.10.2/24
      vlan.20:
        id: 20
        link: eth2
        addresses:
          - 10.0.20.2/24
      vlan.30:
        id: 30
        link: eth2
        addresses:
          - 10.0.30.2/24
