from distro import codename
from logging import getLogger

logger = getLogger(__name__)


def check_for_supported_os(config, provider):
    """
    Checks if VNet is running on a supported OS for a provider
    :param dict config: The config generated by get_config()
    :param str provider: The provider to check OS support for
    :return: bool: True if the current OS is supported, False otherwise
    """
    logger.debug("Checking if your os is supported for provider {}".format(provider))
    return codename().lower() in config["providers"][provider]["supported_operating_systems"].lower()
