name: Black

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'black==21.9b0'
      - name: Analysing code formatting with Black
        run: |
          black --check --diff --line-length 140 --target-version py36 vnet_manager
